/*
----------------------------------------------------------------------------------------------------------------
-- Création de la base de donnée -----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
*/
CREATE DATABASE "Wonderdb";

USE "Wonderdb"


/*
----------------------------------------------------------------------------------------------------------------
-- Création des tables -----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
*/


/*
# ----------------- admin -----------
*/
 
CREATE TABLE user_admin
(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	firstname VARCHAR(63) NOT NULL, 
	lastname VARCHAR(63) NOT NULL, 
	email VARCHAR(63) NOT NULL, 
	password VARCHAR(255) NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT GETDATE(), 
	UNIQUE (email)
);
INSERT INTO user_admin  (firstname,lastname ,email ,password )
VALUES
 ('mustapha','hadjal','hadja@live.fr', '$2a$12$AyOspfTo0FWmbtHuzqpxCOdZvjQHNPGCCu.emPklrzrpDJqdrf9/.')
;
SELECT * FROM user_admin

SELECT * FROM user_admin WHERE email ='hadja@live.fr'
/*
# ----------------- agency -----------
*/

CREATE TABLE agency
(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	slug VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	logo_url VARCHAR(511) NOT NULL, 
	createdAt DATETIME  NOT NULL DEFAULT GETDATE() , 
	bio VARCHAR(2047) NOT NULL, 
	address VARCHAR(255) NOT NULL, 
	agencyCreation DATE NOT NULL  , 
	encours FLOAT  DEFAULT 0,
	fund BIGINT DEFAULT 0,
	effective INT DEFAULT 0,
	MajorityShareholder VARCHAR(255)  ,
	UNIQUE (slug) ,
);
  
 select * from agency
 /*
	Scraped with a custom made python script 

 ('agence-AEW PATRIMOINE (EX-CILOGER)', 'AEW PATRIMOINE (EX-CILOGER)','AEW Ciloger est le nouveau nom de Ciloger, dont l’activité est la gestion des fonds grand public. C''est une filiale d’AEW S.A. issue du rapprochement entre AEW Europe et Ciloger en 2016. La société de gestion gère ainsi 22 SCPI (dont ACTIPIERRE EUROPE et Pierre Plus),  et 2 OPCI grand public soit plus 24 milliards d’€. pour le compte d’environ 80 000 associés. Elle se classe parmi les trois premiers acteurs de la gestion de l’épargne immobilière et son patrimoine est composé de tous les principaux secteurs du marché immobilier (bureau, commerce, résidentiel) répartis entre la France et les principales villes de la zone euro.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/aew_ciloger-5f5f4342996d2.png','22 Rue du Dr Lancereaux, 75008 Paris, France','2016',24000.00,25,110000,'Natixis Global Asset Management (60%) / Banque Postale (40%)'),
('agence-ALDERAN', 'ALDERAN','La société Alderan, est une société de gestion de portefeuille immobilier indépendante, appartenant au groupe Ojirel, acteur sur le secteur de l’immobilier tertiaire depuis une vingtaine d’années. Alderan agit sur l’ensemble du cycle de détention d’actif : acquisition, gestion et revente. Elle est aussi la société de gestion de la SCPI Activimmo.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/alderan-5f5f4d05b9405.jpeg','22 Rue de Courcelles, 75008 Paris, France','2015',360.00,67,1,'Groupe Ojirel')

('agence-Allianz Immovalor', 'Allianz Immovalor','La société de gestion Immovalor Gestion, créée en 1983, est devenue Allianz Immovalor en octobre 2022. Elle gère les SCPI de rendement Allianz Pierre (bureaux) et Allianz Home (résidentiel) ainsi que 8 SCPI fiscales (fermées à la souscription). Son portefeuille global, qui comprend entre autres des sociétés civiles immobilières, totalise 5,3 milliards d’euros d’actifs immobiliers sous gestion. La société de gestion de portefeuille (depuis 2007) a obtenu l’agrément n° GP-07000035 de l’Autorité des marchés financiers en date du 26 juin 2007.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/allianz_immovalor-6343e5d7206f4.png','tour Allianz One, 1 Cours Michelet, 92076 La Défense, France','01/11/1983','4600.00','16','27000','Jean-Pierre QUATRHOMME'),
('agence-ALTIXIA REIM', 'ALTIXIA REIM','ALTIXIA REIM est une société gestion de portefeuille au capital de 600 000 €, dont le siège social est sis à Paris 8ème, 30 avenue de Messine ET agréée par l’Autorité des Marchés Financiers en date du 3 novembre 2015 sous le numéro GP.15000028 La société de gestion ALTIXIA REIM propose trois solutions d’investissement : Scpi (Scpi Altixia Commerces et Scpi Altixia Cadence XII), OPCI (Organisme de Placement Collectif en Immobilier) et un Club DEAL qui est une solution immobilière personnalisée. La société de gestion Altixia REIM gère actuellement près de 495 Millions d’euros d’actifs immobiliers. La société de gestion Altixia REIM a pour objectif de proposer des solutions immobilières adaptées aux exigences et besoins des clients.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/altixia_reim-5f5f50366a18c.jpeg','2 Avenue Marceau, 75008 Paris, France','2015','406.00','2','0','Xavier Alvarez-Roman'),

('agence-AMUNDI', 'AMUNDI','Le groupe Amundi a vu le jour en 2009. Amundi est le fruit du rapprochement entre la Société Générale et le Crédit Agricole souhaitant s’unir pour développer leurs activités immobilières et de gestion d’actifs. Aujourd’hui, la société de gestion représente environ 866 milliards d’actifs gérés ce qui en fait le numéro 1 en Europe et lui permet de se positionner dans le top 10 mondial avec 2000 clients institutionnels et 100 millions de clients. Par l’intermédiaire de sa branche immobilière, la société de gestion se repose sur 45 ans d’expérience. Elle est aujourd’hui un des deux acteurs majeurs de la gestion SCPI en France avec 7,9 milliards de capitalisation. Au travers d’une centaine de fonds immobiliers dont une quinzaine de fonds réservés aux banques privées et aux institutionnels, Amundi Immobilier s’appuie sur ses nombreuses compétences pour développer des produits d’épargne de qualité. Le groupe Amundi gère les SCPI suivantes : Rivoli Avenir Patrimoine, Edissimmo et Genepierre.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/amundi_asset_management-5f5f710b7c93a.png','90 Boulevard Pasteur, 75015 Paris, France','2009','1592000.00','195','4725','Groupe Crédit Agricole'),
('agence-Arkéa REIM', 'Arkéa REIM','La société de gestion Arkéa REIM se décrit comme un "créateur de solutions d’épargnes immobilières innovantes". Elle place en effet la transition au cœur de sa stratégie d’investissement en ciblant des biens immobiliers qui sauront faire face aux défis futurs. Dans l’accompagnement des transitions immobilières, le gestionnaire prend systématiquement en compte les critères ESG (environnementaux, sociaux et de gouvernance) dans ses démarches.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/arkea_reim-63e8c75ee02db.png','72 Rue Pierre Charron, 75008 Paris, France','2021','804.20','3','0','Arkéa IS'),
 ('agence-ATREAM', 'ATREAM','Atream est une société gestion de portefeuille spécialisée dans le secteur hôtelier. Créée en 2008 et agréée par l’AMF sous le numéro GP-13000011, elle gère actuellement 2 Scpi dont la SCPI Atream Hôtels et la Scpi Pierre Altitude. La société de gestion est spécialisée dans la création et la gestion des fonds immobiliers (Hôtels et résidences hôtelières) destinés aux investisseurs privés et institutionnels. La société de gestion s’appuie sur le savoir faire et le professionnalisme de ses 24 collaborateurs et de son équipe dirigeante. Elle a vocation à proposer des solutions immobilières adaptées aux exigences et besoins des clients','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/atream-5f6367cd222cd.jpeg','153 Rue du Faubourg Saint-Honoré, 75008 Paris, France','2008','3500.00','300','43','Pascal Savary et Grégory Soppelsa'),
('agence-BNP PARIBAS REIM', 'BNP PARIBAS REIM','BNP Paribas REIM (Real Estate Investment Management) est une société de gestion d’actifs immobiliers commerciaux en Europe, filiale du groupe bancaire BNP PARIBAS. Elle est présente dans 7 pays européens dont : la France, l’Allemagne,l’Italie, le Royaume-Uni, l’Espagne, la Belgique et le Luxembourg. Aujourd’hui, la société de gestion BNP Paribas REIM gère plus de 30 milliards d’actifs immobiliers commerciaux en France et en Europe. Elle a pour objectif d’offrir aux investisseurs institutionnels et privés la possibilité d’investir en immobilier en France et en Europe.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/bnp_paribas_real_estate-5fbd087e15bdd.jpeg','167 QUAI DE LA BATAILLE DE STALINGRAD 92130 ISSY-LES-MOULINEAUX','Février','1010.00','1','5400','Mr Thierry Laroue-Pont'),
('agence-CM-CIC SCPI Gestion', 'CM-CIC SCPI Gestion','La société de gestion CM-CIC SCPI Gestion est une société de gestion de portefeuille créée en 2005 et agréée par L’Autorité des marchés financiers. Elle gère actuellement la SCPI CM-CIC Pierre Investissement spécialisée dans l’immobilier d’entreprise. La société CM-CIC SCPI Gestion se charge de la gestion de la SCPI, recherche, acquisition et entretien des biens immobiliers, recherche de locataire et mise en location des biens immobiliers locatifs. La société de gestion a vu le jour en 2005, depuis elle gère et prend en charge la gestion des SCPI mises en place par le groupe CIC et le Crédit Mutuel avant leur fusion.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/cmcic_scpi_gestion-600040fd1af61.jpeg','2 avenue Jean-Claude Bonduelle 44000 Nantes','2005','80.00','2','0','Crédit Mutuel CIC'),
('agence-Consultim AM', 'Consultim AM','Consultim AM est une société de gestion de type nouvelle génération, créée en 2020 et agréée par l’AMF en date du 28 mai 2020 sous le numéro GP-20000013. La société de gestion fait partie du Consultim Groupe et gère actuellement la SCPI Optimale. Consultim Groupe est un leader sur le marché français et européen. Elle est experte en gestion immobilière et financière depuis 25 ans. Le groupe propose à ses clients privés et institutionnels ainsi qu'aux professionnels du patrimoine immobilier diverses solutions d’investissement.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/consultim_am-5f904c503bbac.png','9 rue Vauban, 33000 Bordeaux','08/01/2020','9000.00','1','200','Andràs BOROS'),
('agence-ATREAM', 'ATREAM','Atream est une société gestion de portefeuille spécialisée dans le secteur hôtelier. Créée en 2008 et agréée par l’AMF sous le numéro GP-13000011, elle gère actuellement 2 Scpi dont la SCPI Atream Hôtels et la Scpi Pierre Altitude. La société de gestion est spécialisée dans la création et la gestion des fonds immobiliers (Hôtels et résidences hôtelières) destinés aux investisseurs privés et institutionnels. La société de gestion s’appuie sur le savoir faire et le professionnalisme de ses 24 collaborateurs et de son équipe dirigeante. Elle a vocation à proposer des solutions immobilières adaptées aux exigences et besoins des clients.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/atream-5f6367cd222cd.jpeg','153 Rue du Faubourg Saint-Honoré, 75008 Paris, France','2008','3500.00','2','43','Pascal Savary et Grégory Soppelsa'),
('agence-CORUM AM', 'CORUM AM','La société de gestion Corum AM a vu le jour en 2011. Corum AM est une société totalement indépendante, son capital est réparti entre les dirigeants fondateurs et WB Finances et Partenaires qui est une holding de Walter Butler. Son activité est exclusivement la gestion d’OPCI et de SCPI (société civile de placement immobilier) pour le compte d’investisseurs privés et institutionnels. La particularité de Corum AM est de réaliser elle même le property management de ses investissements pour le compte de ses SCPI et OPCI. Les associés fondateurs sont reconnus sur le marché pour leur connaissance des marchés immobiliers et leur vision long terme des marchés. Aujourd’hui, près de 4 milliards d’euros d’actifs sont gérés par la société de gestion. C’est la réussite de ses SCPI (Corum Origin,Corum Xl et plus récemment Eurion) qui fait la renommée de cette société de gestion. Grâce à sa stratégie d’opportunité d’investissement en France et à l’étranger, Corum Origin est aujourd’hui une des SCPI incontournable du marché. En 2020, la société de gestion a lancé une nouvelle SCPI dénommée Eurion.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/corum_am-5f65d94cd8a31.jpeg','1 Rue Euler, 75008 Paris, France','2011','2000.00','3','20','Dirigeants'),
('agence-Epsilon Capital', 'Epsilon Capital','Epsilon Capital est une société de gestion qui a été créée en 2021. À travers sa première et unique SCPI à ce jour, Epsilon 360°, la société de gestion investit dans l’immobilier tertiaire de petite taille en France. Epsilon Capital est une structure à taille humaine qui mise sur une grande disponibilité de ses équipes pour privilégier une relation de proximité avec les investisseurs et leur proposer des produits performants.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/eplison_capital-6362622ac8327.png','10 RUE DES TROIS CONILS, 33000 BORDEAUX','2021','16.00','1','0','nc'),
------------NOT VALIDE SYNTAX--------------
('agence-EURYALE AM', 'EURYALE AM','Euryale AM est une société de gestion de portefeuille qui a été créée en 2010. Elle est avant tout une filiale du groupe Elience, qui s’est imposé comme l’un des leaders dans la gestion et l’administration des biens. Euryale AM s’appuie sur l’expertise du groupe Elience et ainsi que sur sa culture immobilière. Elle peut d’ailleurs compter sur son équipe composée d'experts en la matière (la gestion d’actifs immobiliers). La gestion d’actifs immobiliers est le cœur de métier de la société et depuis un certain nombre d’années, elle exerce sa possibilité de faire appel à des experts indépendants dans le cadre de ses investissements immobiliers, notamment pour les SCPI.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/euryale_am-5f6604466eb46.jpeg','14 Rue la Fayette, 75009 Paris, France','2010','2500.00','2','6','Groupe Elience'),
('agence-FIDUCIAL GÉRANCE', 'FIDUCIAL GÉRANCE','Fiducial Gérance fait partie du groupe Fiducial. Pour rappel, ce groupe est leader des services pluridisciplinaires aux entreprises avec différentes activités dans le domaine du droit, de l’audit et le commissariat aux comptes, l’expertise comptable, les organismes agréés, la banque et le conseil, la gestion de SCPI et d’OPCI, l’informatique, la sécurité et le monde du bureau. La société de gestion Fiducial Gérance filiale à 100% du groupe Fiducial, agréée par l’autorité des marchés financiers, gère 2 milliards d’euros d’actifs. C’est aujourd’hui la deuxième société de gestion indépendante du marché. Ces actifs sont répartis sur 7 SCPI (Buroboutic, Ficommerce, Selectipierre 2, Logipierre 3, Capiforce Pierre, Pierre Expansion, Primo 1). Fiducial a également une activité de gestion de 6 groupements forestiers et 5 SCI. Fiducial Gérance est reconnue sur le marché pour sa capacité d’innovation, sa capacité de sourçing de bonnes opérations immobilières et surtout sa capacité à servir aux investisseurs de la performance sur ces différents supports d’investissement.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/fiducial_gerance-5f660515e6913.jpeg','La Défense Cedex, 41 Avenue Gambetta CS 50002, 92928 Paris, France','1997','1750.00','24','65','Groupe Fiducial'),
('agence-Foncière & Territoires', 'Foncière & Territoires','Foncière & Territoires est une société de gestion de portefeuille agréée par l’Autorité des Marchés Financiers en date du 1 er Octobre 2013, sous le numéro GP-13000031. En date du 1er octobre 2014, elle obtient un deuxième agrément conformément à la directive 2011/61/UE AIFM. La société de gestion gère actuellement une seule SCPI dénommée Cap Foncières & Territoires. Cette dernière est née de la fusion des 3 SCPI de rendement suivantes : la SCPI Nord Est Horizon, la SCPI Rhône Alpes Méditerranée et la SCPI Ouest Cap Atlantique. La société de gestion Foncière & Territoires est implantée à LYON, NANTES et NANCY. Elle a pour objectif de réaliser des investissements de qualité en développant son épargne immobilière au travers la SCPI Cap Foncières & Territoires.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/fonciere__territoires-5fd9df138adad.png','21 Quai Antoine Riboud, 69002 Lyon, France','1997','100.00','40','10','Frédéric DURAND'),
('agence-Foncière MAGELLAN', 'Foncière MAGELLAN','Foncière MAGELLAN est une société de gestion de portefeuille lancée en 2010 et agréée par l’autorité des marchés financiers. Elle est spécialisée dans l’investissement et la gestion d'actifs immobiliers dédiés aux investisseurs privés et institutionnels. Dans sa stratégie d’investissement en immobilier, la société de gestion Foncière MAGELLAN se base sur l’immobilier tertiaire neuf localisé principalement en région ainsi que la rénovation des biens immobiliers à forte valeur ajoutée. Actuellement, la société de gestion se charge de la gestion de la SCPI Foncière des praticiens.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/fonciere_magellan-60005e8233646.jpeg','3 Rue Anatole de la Forge, 75017 Paris, France','19/03/2010','900.00','55','49','Amundi'),
('agence-Grand Ouest Gestion d’Actifs', 'Grand Ouest Gestion d’Actifs','Grand Ouest Gestion d’Actifs est une l’une des filiales de la Banque Populaire Grand Ouest. Elle est la société de gestion de portefeuille de la société civile de placement immobilier Atlantique Mur Régions. Grand Ouest Gestion d’Actifs a été créée en 1987, elle dispose d’une expérience de plus de 33 ans dans l’immobilier de bureaux principalement localisé dans les métropoles régionales françaises. Aujourd’hui, la SCPI gérée par Grand Ouest Gestion d’Actifs dispose d’un patrimoine immobilier de 100 immeubles avec plus de 270 entreprises locataires.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/banque_populaire_grand_ouest-5fce033825609.jpeg','15 Boulevard de la Boutière, 35768 Saint-Grégoire','1987','470.00','1','7','BANQUE POPULAIRE GRAND OUEST'),
('agence-Greenman Arth', 'Greenman Arth','La société de gestion Greenman Arth est une filiale du groupe irlandais Greenman, un acteur de premier ordre dans l’immobilier commercial en Allemagne. Spécialisé dans les commerces alimentaires, le groupe gère ainsi plus d’un milliard d’euros d’actifs Outre-Rhin. La société de gestion Greenman Arth est visée par l’AMF afin de pouvoir gérer la SCPI GMA Essentialis.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/greenman_arth-63b5535c8f196.png','1 Rue de la Paix, 75002 Paris, France','2005','890.00','1','60','Groupe Greenman'),
('agence-HSBC REIM', 'HSBC REIM','HSBC REIM France est une société de gestion filiale à 100% de la banque HSBC (HSBC Global Asset Management). Cette société de gestion est agréée par l’AMF. Elle a une activité de gestion immobilière pour des investisseurs professionnels ou particuliers en France. La société de gestion HSBC REIM développe différents savoir-faire dans plusieurs spécialisations comme la gestion des immeubles, la gestion locative, la gestion technique, la gestion comptable, la gestion des associés et le secrétariat général. HSBC REIM gère deux SCPI qui sont Elysées Pierre (SCPI de rendement) et Elysées Résidence 5 (SCPI fiscale).','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/hsbc_reim-5f6606ff6d25c.jpeg','03, avenue des Champs-Elysées - 75008 PARIS','1972','1400.00','2','26','HSBC Global Asset Management'),
('agence-INTER GESTION', 'INTER GESTION','La société de gestion, Inter Gestion, a été créée le 11/04/1988 et agréée par l’AMF en date du 29 Février 2012 sous le numéro n° GP-12000008, au capital social de 240 000 €, dont le siège social est 2, Rue de la Paix 75002 Paris. La société est dédiée à la gestion des actifs immobiliers notamment les commerces, les magasins, les grandes enseignes commerciales, ainsi que les biens à réhabiliter. En 2011, la société de gestion lance sa première SCPI de Rendement : Cristal Rente. Elle dispose actuellement de : 1 SCPI de Rendement, 1 SCPI Déficit Foncier, 8 Scpi Malraux et 3 Scpi Robien/Scellier. L’objet social de la Société Inter Gestion est la direction de toutes associations foncières, le développement de toutes sociétés immobilières, la gestion de portefeuille pour le compte de tiers.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/inter_gestion-5f6607d2d3b02.png','2 Rue de la Paix, 75002 Paris, France','1988','600.00','16','10000','Gilbert Rodriguez'),
('agence-IROKO', 'IROKO','La société de gestion Iroko a vu le jour en 2020. Fintech de l’épargne agréée comme société de gestion par l’AMF, elle a mis sur pied sa première SCPI la même année, à savoir Iroko ZEN. Iroko compte une vingtaine de collaborateurs. Elle a ouvert une partie de son capital à la société d’investissement française Eurazeo en 2021.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/iroko-631db712581a0.png','4 Rue de la Pompe, 75116 Paris, France','2020','0.00','1','0','Fondateurs'),
('agence-KYANEOS AM', 'KYANEOS AM','La société de gestion, Kyaneos AM,a été créée et agréée par l’AMF en date du 26/02/2018 sous le numéro GP-1800002, au capital social de 250 000 €, dont le siège social est 8, rue d’Annanelle – 84 000 Avignon. Kyaneos AM est une nouvelle société dédiée à la gestion des actifs immobiliers notamment l’immobilier résidentiel locatif, elle lance sa première Scpi en date du 11/04/2018 nommée Kyaneos Pierre. L’équipe de de la société de gestion a la certitude de réaliser ses objectifs en se basant sur les trois critères suivants :','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/kyaneos_am-5f6608c4f2370.jpeg','8 Rue d'Annanelle, 84000 Avignon, France','2018','0.00','1','4','Management'),
('agence-LA FRANÇAISE AM', 'LA FRANÇAISE AM','La Française AM est un groupe qui a vu le jour en juillet 2009. Son activité, regroupant 550 collaborateurs à Paris, Hong Kong, Francfort, Luxembourg, Londres, Milan et Madrid est la gestion d’actifs mobiliers et immobiliers (48 milliards sous gestion). La Française AM existe depuis plus de 40 ans et avait pour dénomination UFG LFP. C’est le rapprochement de ces deux entités qui a fait naître La Française AM. Le Crédit Mutuel du Nord Europe fait partie des actionnaires solides de ce groupe indépendant. La gestion immobilière est un des fleurons de ce groupe depuis 1975. La Française REM qui fait partie de La Française Global Real Estate Investment Managers, qui regroupe toutes les activités liées aux investissements immobiliers et notamment aux SCPI. La Française REM est le leader français au niveau de la capitalisation en SCPI à savoir près de 10 milliards d’euros d’actifs immobiliers sur 20 SCPI ( dont Épargne foncière, SELECTINVEST 1, LFP Europimmo, Pierval Santé, Multimmobilier 2, LFP Opportunité immo ) et 14 OPCI.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/la_francaise_am-5f660b5c975cd.png','128 boulevard Raspail, 75006 PARIS, France','1975','9430.00','58','115','Crédit Mutuel'),
('agence-My SHARE Company', 'My SHARE Company','My SHARE Company est une société de gestion de portefeuille appartenant aux actionnaires DROUOT ESTATE d’AXA France et Atland Voisin. En 2018, elle obtient l’agrément de l’autorité des marchés financiers. Elle a pour objectif de réunir le savoir-faire de Drouot Estate d’Axa France et du groupe Atland Voisin pour réaliser des investissements immobiliers de qualité et proposer des solutions d’épargne immobilière dédiées aux clients d’AXA. La Société de gestion est présidée actuellement par Philippe Ifegane, ayant plus de 30 ans d'expérience dans la gestion des fonds d’investissement tels que les SCPI et OPCI. My Share Company est la société de gestion de la SCPI MyShareSCPI.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/my_share_company-60095017310f7.png','66/74, Rue de la Victoire 75009 Paris France','05-12-2017','100.00','1','2','Drouot Estate d’Axa France et Atland Voisin'),
('agence-NORMA CAPITAL', 'NORMA CAPITAL','Norma Capital est une société de gestion de patrimoine issue du rachat de Glad Patrimoine par d’anciens dirigeants de la société de gestion Vendôme Capital Partners. Agréée par l’AMF sous le Numéro GP-16000017, elle gère actuellement plusieurs fonds immobiliers notamment des SCPI des OPCI ET SCI Club Deal. La stratégie de la société de gestion Norma Capital est basée sur le dialogue, la transparence et l’efficacité de son équipe dirigeante. Actuellement, Norma Capital gère deux Scpi : la SCPI Vendôme Régions, et la SCPI Fair Invest.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/norma_capital-5f660c5503039.jpeg','105 Boulevard Haussmann, 75008 Paris, France','2017','550.00','0','7','Management'),
('agence-Novaxia Investissement', 'Novaxia Investissement','Novaxia Investissement filiale de Novaxia est une société de gestion de portefeuille créée le 8 juillet 2014 et agréée par l’autorité des marchés financiers. Novaxia Investissement est spécialisée dans l’épargne immobilière gère actuellement la SCPI Neo qui est une SCPI d’entreprise dont la stratégie d’investissement et de gestion est fondée sur la transformation urbaine. La société de gestion de portefeuille figure dans le Palmarès des Fournisseurs 2020 de Gestion de fortune. Elle a obtenu le prix du Lauréat dans la catégorie Capital investissement immobilier.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/novaxia_investissement-600d542e14c73.jpeg','3 Rue des Italiens, 75009 Paris, France','08/07/2014','450.00','2','600','Novaxia'),
('agence-PAREF', 'PAREF','Le groupe Paref a été fondé en 1997 par Hubert Lévy-Lambert avec 10 associés. Ce groupe, introduit en bourse en 2005, est spécialisé dans la constitution de patrimoine en région parisienne. Paref Gestion est une société de gestion créée en 1991 et agréée par L’AMF depuis le 19 février 2008 est une filiale à 100% de Paref. Depuis le 16 juillet 2014, la société de gestion est aussi agréée par l’AIFM. Elle est cotée sur Euronext Paris. La spécialité de Paref Gestion est la création ainsi que la gestion pour le compte de tiers de solution de placement immobilier. La société de gestion gère actuellement 6 SCPI (Pierre 48, Novapierre 1, Novapierre Allemagne, Interpierre France, Capiforce Pierre et Atlantique Pierre 1). Elle gère également 2 OPCI (Vivapierre et 54 Boetie). La société de gestion est reconnu pour sa capacité à innover sur le marché avec des SCPI comme Pierre 48 qui est une SCPI de capitalisation ou plus récemment Novapierre Allemagne qui est une SCPI à capital variable constituée d’un parc immobilier Allemand.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/paref-5f674ce0061fb.jpeg','153 Boulevard Haussmann, 75008 Paris, France','1991','2200.00','7','15','Paref'),
('agence-PERIAL AM', 'PERIAL AM','Le groupe PERIAL AM est depuis 50 ans un acteur majeur du monde de l’épargne immobilière. Le groupe, dirigé par la famille Cosserat, a su conserver son indépendance depuis 1966 et compte aujourd’hui près de 500 collaborateurs. L’expertise de PERIAL repose sur trois filiales complémentaires, Perial Asset Management (gestion de fonds immobiliers), Perial Property Management (gestion d’immeubles) et Perial Développement (promotion immobilière). PERIAL AM gère 4 SCPI (PF1, PFO, PF Hospitalité Europe et PFO2) qui représentent une capitalisation de 4,5 Milliards d’euros, et plus de 45 000 associés. De PF1, 1ère SCPI en 1966, désormais PF Grand Paris à PFO2, 1ère SCPI environnementale en 2009, à PF Hospitalité Europe en 2020,  PERIAL Asset Management innove sans cesse pour assurer à ses clients des performances durables.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/perial_am-5f674e2a9765f.png','261 Rue de Paris, 93100 Montreuil, France','1966','2370.00','4','500','Famille Cosserat'),
('agence-PRIMONIAL REIM', 'PRIMONIAL REIM','La société de gestion Primonial REIM existe depuis 2011. Il s’agit d’une filiale du groupe Primonial existant lui depuis 1989 et est un des leaders français du secteur de la gestion de patrimoine. Son activité est la création de solutions d’investissement liées aux marchés immobiliers. Primonial REIM a développé une gamme de SCPI avec chacune ses particularités. Aujourd’hui, elle gère un encours de 4,2 milliards d’euros dont 44% en SCPI, réparti sur 16 fonds et représentant 900 000 m2. Sa SCPI Primopierre a dépassé le milliard de capitalisation. L’actionnariat de Primonial est réparti de la manière suivante: 75% par les cadres dirigeants et 25% par Naxicap Partners (Natixis). Un rapprochement avec W Finance en 2011 permet aujourd’hui au groupe de compter environ 40 000 clients.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/primonial_reim-5f6750b498d89.gif','6-8 rue Général Foy – 75008 Paris','1989','22000.00','16','30','Nexicap, Salariés'),
('agence-Remake Asset Management', 'Remake Asset Management','Remake Asset Management est une société de gestion de portefeuille qui a été créée en 2021. Spécialisée dans l’investissement immobilier, Remake AM entend mettre l’épargne au cœur de sa stratégie d’adaptation à la transformation des territoires périurbains. Remake Live est à ce jour l’unique SCPI gérée par la société de gestion.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/remake_asset_management-6343e587c1f61.png','16 Rue Washington, 75008 Paris, France','15/01/2021','0.00','1','0','Nicolas Kert et David Seksig'),
('agence-SOFIDY', 'SOFIDY','Sofidy est un acteur indépendant de référence de la gestion d’actifs immobiliers en France et en Europe depuis une trentaine d’années. Le groupe est né en 1986 et gère aujourd’hui plus de 3 milliards d’euros représentant 1,4 million de mètres carrés pour le compte de près de 30 000 porteurs de parts. Ce patrimoine géré est réparti sur 6 SCPI (Dont Immorente et Efimmo 1), mais aussi une foncière et un OPCI. Sofidy est divisée en deux filiales spécifiques à savoir :','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/sofidy-5f67532f5c4c6.png','303 Square des Champs Elysées, 91080 Évry-Courcouronnes, France','1986','6200.00','8','152','Famille FLAMARION'),
('agence-SOGENIAL IMMOBILIER', 'SOGENIAL IMMOBILIER','Sogenial Immobilier est une société de gestion de portefeuille, agréée depuis 2012 par l’AMF. Elle est spécialisée dans la gestion des SCPI et OPCI. Forte d'une expérience de 38 ans dans le management, elle propose aux investisseurs ses conseils en investissement et en gestion de fonds immobiliers. La société de gestion gère actuellement 5 OPPCI et 2 SCPI dont Cœur de Ville et Cœur de Régions. Dans sa gestion, Sogenial immobilier s’appuie sur son savoir-faire et sur la culture immobilière et financière de ses actionnaires et de ses dirigeants. La société de gestion investit ses Fonds en immobilier d’entreprise (bureaux, activité, commerce…) dans toute la France. La gestion d’actifs immobiliers est le cœur de métier de la société de gestion de portefeuille et ce depuis 1981.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/sogenial_immobilier-5f67549148718.jpeg','29 Rue Vernet, 75008 Paris, France','1981','270.00','13','80','Jean-Marie SOUCLIER'),
('agence-Swisslife Reim', 'Swisslife Reim','Swisslife REIM est une des société learders dans la gestion d’actifs immobiliers en Europe. En France, elle est un acteur important de l’immobilier avec près de 10 milliards d’euros d’actifs et 380 actifs gérés. La société a été créée en 2007, elle compte plus d’une centaine de collaborateurs dotés d’une expertise avérée sur les marchés aussi bien français qu’européens et qui interviennent dans de nombreux domaines de l’immobilier ( professionnel et résidentiel). Swisslife Reim s’occupe de la gestion de plus de 380 actifs immobiliers et de 39 fonds d’investissements professionnels.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/swiss_life_asset_management-5f6ca81434d8e.png','2 B QUAI D'ARENC - JACQUES SAADE - 13002 MARSEILLE','2007','1000.00','39','10','Swisslife'),
('agence-Theoreim', 'Theoreim','Theoreim est une société de gestion immobilière créée en 2019. Elle pilote divers véhicules d’investissement, dont la SCPI LOG IN, lancée en septembre 2022. Elle travaille en architecture ouverte avec des partenaires spécialisés dans les différentes classes d’actifs immobiliers, en privilégiant une stratégie d’investissement à l’échelle européenne.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/theoreim-636a55d5e3ef9.jpg','10 Rue d'Uzès, 75002 Paris, France','27/02/2020','632.28','3','10','Romain WELSCH'),
('agence-UNOFI', 'UNOFI','La société de gestion Unofi Gestion d’Actifs organisée autour de la Société par Actions Simplifiée Unofi gère actuellement la SCPI Notapierre, les fonds communs de placements et les investissements d’Unofi-assurances. Son siège social est sis à 2, rue Montesquieu, CS 11120 75039 PARIS. Le Groupe bénéficie de l'expérience de l’équipe dirigeante composée de 320 collaborateurs dont 53 % sont situés en directions régionales et 47 % au sein des autres directions du groupe. La société de gestion de portefeuille Unofi-Gestion d’actif se charge de la sélection, la recherche et l’acquisition des actifs immobiliers de la SCPI Notapierre ainsi que la recherche d’associés et de locataires.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/unofi-6019a7c47c712.png','2, rue Montesquieu, CS 11120 75039 PARIS cedex','20/12/2002','9654.00','4','320','AXA FRANCE VIE & AFI.ESCA'),
('agence-URBAN PREMIUM', 'URBAN PREMIUM','Urban Premium est une société de gestion de portefeuille, agréée par l’AMF en date du 08 juin 2010 sous le numéro GP- 10000021, au capital social de 1 500 000 €, dont le siège social est 10, rue du Chevalier Saint George 75001 Paris, France. Urban Premium est une société de gestion créé le 22/03/2010 et est dédiée à la Gestion de fonds d’investissement immobilier. Elle gère une gamme de SCPI d’habitation et de commerce, orientées sur l’investissement immobilier de centre-ville. La société de gestion Urban Premium gère 10 Scpi fiscales : SCPI DÉFICIT FONCIER (Urban Pierre, Urban Pierre 2, Urban Pierre N°3 et Urban Pierre N°4), SCPI Pinel (Urban Vitalim N°2), SCPI Malraux (Urban Prestigimmo N°3, Urban Prestigimmo 2 et Urban Prestigimmo), SCPI Scellier (Urban Patrimoine, Urban Patrimoine 2) Actuellement, la société de gestion ouvre 03 Scpi : Une Scpi de rendement : Urban Cœur de Commerce et deux Scpi Malraux : Urban Prestigimmo N°4 & Drouot Estate Immocentre. Dans sa stratégie d’investissement, la société de gestion s’appuie sur le savoir-faire et le professionnalisme de son équipe dirigeante.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/urban_premium-5f67562a77d63.jpeg','10 Rue du Chevalier de Saint-George, 75001 Paris, France','2010','150.00','5','7','Franck Temim'),
('agence-VOISIN GROUPE ATLAND', 'VOISIN GROUPE ATLAND','La société de gestion VOISIN GROUPE ATLAND est une société de gestion indépendante. Son siège est à Dijon depuis son lancement. L’ancrage régional est l’ADN de cette société de gestion et se fait sentir dans la gestion de ses SCPI. Effectivement, les investissements sont orientés vers les capitales régionales. VOISIN GROUPE ATLAND, société de gestion agréée par l’AMF a une approche de gestion prudente. Son rapprochement en 2015 de la foncière ATLAND lui permet aujourd’hui de devenir un acteur incontournable sur le marché des SCPI. Acteur historique du marché, Voisin a été créé en 1947 avec une activité de transaction et promotion immobilière et a notamment lancer sa première SCPI en 1968 avec IMMO PLACEMENT qui est une SCPI régional. Aujourd’hui, en plus de ses activités de promotion immobilière et d’administration de bien, 5 SCPI sont gérées par la société de gestion. Ces SCPI (Epargne Pierre, Immoplacement, Foncièreremusat, Immauvergne, Epargne Habitat) représentent un patrimoine d’environ 300 millions d’euros réparti sur 400 actifs.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/voisin_groupe_atland-5f6756f28f51e.png','15 Place Grangier, 21000 Dijon, France','1968','1300.00','7','30','Foncière Atland'),

 */
INSERT INTO agency (slug,title,bio,logo_url,address,agencyCreation,encours,fund,effective,MajorityShareholder) VALUES
('agence-Epsilon Capital', 'Epsilon Capital','Epsilon Capital est une société de gestion qui a été créée en 2021. À travers sa première et unique SCPI à ce jour, Epsilon 360°, la société de gestion investit dans l’immobilier tertiaire de petite taille en France. Epsilon Capital est une structure à taille humaine qui mise sur une grande disponibilité de ses équipes pour privilégier une relation de proximité avec les investisseurs et leur proposer des produits performants.','https://fortunyconseil.fr/Access/public/uploads/images/societe_gestion/eplison_capital-6362622ac8327.png','10 RUE DES TROIS CONILS, 33000 BORDEAUX','2021','16.00','1','0','nc')

-----Testing--------

SELECT *  FROM Agency INNER JOIN scpi ON  agency.id = scpi.parentAgency where agency.slug = 'agence-AEW PATRIMOINE (EX-CILOGER)'
SELECT *  FROM Agency left JOIN scpi ON  agency.id = scpi.parentAgency where agency.slug ='agence-AEW PATRIMOINE (EX-CILOGER)'
select * from agency (select title from scpi where scpi.parentAgency = Agency.id ) as title where slug = 'agence-AEW PATRIMOINE (EX-CILOGER)'

------------- SCPI ------------------------}
  

CREATE TABLE scpi
(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	createdAt DATETIME  NOT NULL DEFAULT GETDATE() ,
	parentAgency INT NOT NULL,
	slug VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL, 
	inOurSelection BIT  DEFAULT 0, 
	lifeInsurance BIT  DEFAULT 0, 
	type VARCHAR(255) NOT NULL, 
	category VARCHAR(255) NOT NULL, 
	localisation VARCHAR(255) NOT NULL, 
	distributionRate FLOAT NOT NULL DEFAULT 0 ,
    partPrice FLOAT NOT NULL DEFAULT 1,
    capitalisation BIGINT NOT NULL,
	scpiCreation DATE NOT NULL  , 
    profil VARCHAR(255) NOT NULL,
    history VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
	capitalType VARCHAR(255) Not NULL,
	minSub INT Not NULL DEFAULT 1,
	periodOfEnjoyment VARCHAR(255),
	subscriptionFee FLOAT DEFAULT 0 ,
	gestionFee FLOAT DEFAULT 0 ,
	visaAMF VARCHAR(255),
);
ALTER TABLE scpi
ADD CONSTRAINT fk_scpi_parentAgency FOREIGN KEY (parentAgency)
REFERENCES agency (id)
ON DELETE CASCADE
INSERT INTO scpi (parentAgency,slug,title,inOurSelection,lifeInsurance,type,category,localisation,distributionRate,partPrice,capitalisation,scpiCreation,profil,history,description,capitalType,minSub,periodOfEnjoyment,subscriptionFee,gestionFee,visaAMF) VALUES

('18','SCPI-ALLIANZ-PIERRE','ALLIANZ PIERRE',0,1,'SCPI de Rendement','Diversifiée','Zone Euro','4.37','1030','956.00','11/03/2015','Lancée en 2015, la SCPI Eurovalys est investie exclusivement sur le marché immobilier allemand dont le marché immobilier professionnel présente de réelles opportunités. En effet, elle a fait le choix de concentrer ses investissements en immobilier de bureaux (notamment des actifs de bureaux) au sein de la première puissance économique européenne. Elle constitue donc un véhicule d’épargne immobilière à destination d’une clientèle composée de particuliers mais aussi d’investisseurs institutionnels en leur permettant de diversifier leur patrimoine. En outre, elle délivre un rendement aux investisseurs, un rendement net, en raison de la convention fiscale franco-allemande et dispose d’un parc immobilier de qualité dont les actifs sont sélectionnés selon des critères très rigoureux.','La SCPI Eurovalys a été lancée à la commercialisation en Juillet 2015. Elle est majoritairement composée d’actifs d’entreprise ( bureaux) en Allemagne. Il s’agit donc d’une SCPI européenne à part entière. En effet, elle a fait le choix de se spécialiser sur le marché immobilier professionnel allemand afin de faire bénéficier à ses investisseurs, de revenus potentiels, le dynamisme de l’économie allemande et de son marché immobilier mais aussi de la fiscalité. Depuis sa création, la SCPI a toujours généré un rendement en ligne avec sa politique de gestion. De même, son prix de part a connu une augmentation passant de 1000 euros à 1015 euros désormais. La SCPI est gérée par Advenis Reim, une société de gestion de SCPI qui compte lus de 734 M d’€ de capitalisation.',
'Pour rappel, la SCPI Eurovalys est une SCPI de rendement à capital variable, qui investit exclusivement sur l’immobilier d’entreprise Allemand. Son patrimoine est composé de 21 actifs, ce qui représente une surface de plus de 200 000 mètres carrés. L’ensemble de ce patrimoine comprend des bureaux qui sont répartis dans les principales villes allemandes. Au 3ème trimestre 2020, le patrimoine de la SCPI se répartit géographiquement comme suit : - 26% à Munich, 25% à Cologne, 16% à Francfort, 13% à Dusseldorf, 5% à Brême, 4% à Hanovre, 4% à Caimersheim, et % à Wolfsburg. L’Allemagne est un des marchés incontournables de la zone euro notamment en matière d’immobilier. Elle est à la fois la première puissance économique en Europe et a une économie dynamique avec un taux de chômage parmi les plus faibles d’Europe.','Capital variable','1','1er jour du 6ème mois','11.40','12.00','18-24')

sp_rename 'scpi.inOurSelection', 'DansNotreSelection', 'COLUMN';
-----Testing--------
delete  from scpi where id =11
select * from agency
select * ,(select title from agency where agency.id = scpi.parentAgency ) as agencyparent from scpi
delete from scpi where id=6
select * from scpi where title like 'Advenis REIM' and lifeInsurance = 1
SELECT * FROM scpi WHERE id is not null  AND (  category = ' '   OR  category = 'Commerce'   ) 
 SELECT * FROM scpi WHERE id is not null   and  (category ='Bureau' OR  category ='Commerce')
 SELECT COUNT(*) AS count  FROM scpi WHERE title = 'PIERRE PLUS'

 SELECT * ,(select title from agency where agency.id = scpi.parentAgency ) as agencyparent FROM scpi WHERE id  IS NOT NULL   AND (  type = 'SCPI de rendement'   )